RepoName: LYH-RAIN/nidemn
RunCommand: |
  echo "start run command"
SourceCodePath: .
CommandTimeout: 3600
SecurityGroupPorts:
- 80
RuntimeType: LinuxShell
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: SourceCode
ServiceBuildRegion: ap-southeast-1
ImageId: '"{{resolve:oos:aliyun/services/computenest/images/aliyun_3_2104_go_1_22}}"'
RegionId: cn-hangzhou
CustomParameters: ''
Owner: LYH-RAIN
Branch: main
Platform: github
